### ISSUE TITLE
PHP 8.4 deprecated warning

### ISSUE THREAD

**Issue by apfelfish** [Vectorface/GoogleAuthenticator#8]
Issue with PHP 8.4.1:
 PHP Deprecated: Vectorface\GoogleAuthenticator::getCode(): Implicitly marking parameter $timeSlice as nullable is deprecated, the explicit nullable type must be used instead in /vectorface/googleauthenticator/src/GoogleAuthenticator.php on line 61

Needs to be: 
?int $timeSlice = null

**Comment by francislavoie** [comment]
Thanks! Fixed in 5efaef702ef6210b43351cf113c37484c2cdf80c, tagged https://github.com/Vectorface/GoogleAuthenticator/releases/tag/v3.3
